language: php

php:
  - nightly

sudo: false
    
env: 
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1 SHOW_ONLY_GROUPS="FAIL,XFAIL,BORK,WARN,LEAK,SKIP"

install:
  - phpize
  - ./configure
  - make

before_script:
  - phpenv config-rm xdebug.ini

script: 
  - TESTS="--show-diff" make test

